### ISSUE TITLE
安装包时缺少 static 文件夹

### ISSUE THREAD

**Issue by chiaki64** [ethe/pygraphy#1]
在上手的时候遇到了一个错误

```
FileNotFoundError: [Errno 2] No such file or directory: '.../site-packages/pygraphy/static/playground.html'
```

排查发现是 site-packages 里的该包缺少了 static 文件夹，需要手动 cp playground.html 进去，原本以为是有意为之的，但是看了 setup.py 后感觉不像，使用 pipenv / pip 的最新版 install 都可以复现( macOS 10.14.2 / Python 3.7.2 )，有 types 文件夹但是缺少了 static，不知道其他人有遇到这个情况吗？

**Comment by ethe** [comment]
Wait a second, I will check it right now.

**Comment by ethe** [comment]
0.0.5 released, please try to upgrade, I think I have already fixed it, thank you and sorry.

**Comment by ethe** [comment]
Closed for now.

**Comment by chiaki64** [comment]
Yep, there is no problem now.
