### ISSUE TITLE
Possible issue with field name cases

### ISSUE THREAD

**Issue by chiaki64** [ethe/pygraphy#24]
First, the document mentioned 

> Pygraphy would try to translate all fields name from snake case to camel case.

Here is my test code

```python
class TestInput(pygraphy.Input):
    normal: str
    snake_case: str
    camelCase: str


class Response(pygraphy.Object):
    result: str
    snake_result: str
    camelResult: str


class Query(pygraphy.Query):

    @pygraphy.field
    def address(self, t: TestInput) -> Response:
        return Response(result=t.normal,
                        snake_result=t.snake_case,
                        camelResult=t.camelCase)
```

The playground shows the scheme

```python
type Response {
  result: String!
  snakeResult: String!
  camelResult: String!
}

input TestInput {
  normal: String!
  snakeCase: String!
  camelCase: String!
}
```

Execute the query and it returns error
```
# query 1
query Address {
  address(t: {
    normal: "str"
    snake_case: "str"
    camelCase: "str"
  }) {
  	result
        snakeResult
  	camelResult
  }
}
# resp
error with camelCase

----------
# query 2
query Address {
  address(t: {
    normal: "str"
    snakeCase: "str"
    camelCase: "str"
  }) {
  	result
        snakeResult
  	camelResult
  }
}
# resp
error with snakeCase

----------
# query 3
query Address {
  address(t: {
    normal: "str1"
    snake_case: "str2"
    camel_case: "str3"
  }) {
  	result
        snake_result
  	camelResult
  }
}
# resp
error with camel_case
```

No matter how we write `camelCase`(`camelCase` or `camel_case`), it is wrong. And the hint of `snake_case` is `snakeCase` but `snakeCase` doesn't work.

Same with Input, the Response field `snake_result` work well with both `snake_result` and `snakeResult`. Bug field `camelResult` doesn't work with both `camel_result` or `camelResult`.

I think this should be a bug, you can see more detail in this [test case](https://github.com/ethe/pygraphy/blob/2d24ba57199efd2c3b31d751f7dd787fe7f0b21e/tests/test_execution.py#L161-L222)  , though the code was not enough pythonic :)

**Comment by ethe** [comment]
Fixed with #25
